### ISSUE TITLE
Privacy API does not seem implemented correctly

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuser101/moodle-block_rewardstally#1]
I appreciate the attempt to have the privacy API implemented. However, it does not seem to work well.

* The external location link seems to be described by `privacy:metadata:lti_client` which does not exist
* No actual information is shown at Site administration > Users > Privacy and policies > Plugin privacy registry

**Comment by moodleuser101** [comment]
* Fixed the broken language string ("lti_client" -> "rewards_api")
* implemented the \core_privacy\local\request\data_provider interface to get the plugin to show up correctly in the plugin privacy registry
