### ISSUE TITLE
block_rewardstally.php must not require login like this

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuser101/moodle-block_rewardstally#2]
This line https://github.com/moodleuser101/moodle-block_rewardstally/blob/e863792eef401b18a33db0eacbe104367823afab/block_rewardstally.php#L33 effectively causes that the site is no longer usable without login.

It should not be like that - that is inappropriate change of the site behaviour affected by the block presence.

The block should just handle login status in the `get_content()` method. E.g. return empty for unauthenticated users or so.

p.s. please note that the user can still log in as a guest user.

**Comment by moodleuser101** [comment]
OK, I thought this affected the block, not the site. Also, I have implemented some user login checks later in the block eg line 67 which I didn't have when I put the require_login();. I'll remove the require_login();

**Comment by mudrd8mz** [comment]
Yeah. Library code like this script can be (and is) loaded in various situations. The other consequence was that it was not actually possible to uninstall the plugin easily via command line:
```
Uninstalling block_rewardstally
Default exception handler: Unsupported redirect detected, script execution terminated Debug: 
Error code: redirecterrordetected
* line 2843 of /lib/weblib.php: moodle_exception thrown
* line 2744 of /lib/moodlelib.php: call to redirect()
* line 33 of /blocks/rewardstally/block_rewardstally.php: call to require_login()
* line 2029 of /lib/blocklib.php: call to include_once()
* line 1991 of /lib/blocklib.php: call to block_load_class()
* line 151 of /lib/classes/plugininfo/block.php: call to block_instance()
* line 196 of /lib/adminlib.php: call to core\plugininfo\block->uninstall_cleanup()
* line 1515 of /lib/classes/plugin_manager.php: call to uninstall_plugin()
```

Thanks for fixing this.
